import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';
import { playXP } from './xp-audio.js';
let scene,camera,renderer,car,clock,phase=0,t=0,particles=[],npcs=[];
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.45,metalness:.15});}
function glass(c){return new THREE.MeshPhysicalMaterial({color:c,roughness:.08,metalness:.05,transparent:true,opacity:.38,transmission:.35});}
function cube(w,h,d,m){const x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.castShadow=true;x.receiveShadow=true;return x;}
function cyl(r,h,m){const x=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,48),m);x.castShadow=true;return x;}
function sphere(r,m){const x=new THREE.Mesh(new THREE.SphereGeometry(r,32,18),m);x.castShadow=true;return x;}
function makeCar(){const g=new THREE.Group();const body=cube(3,.5,1.35,mat(0x0f8fe8));body.position.y=.45;const cabin=cube(1.1,.55,1,glass(0xbff4ff));cabin.position.set(.2,.92,0);const nose=cube(1,.35,1.1,mat(0xffd84d));nose.position.set(1.35,.35,0);g.add(body,cabin,nose);for(const x of[-1.05,1.05])for(const z of[-.76,.76]){const w=cyl(.28,.22,mat(0x111111));w.rotation.z=Math.PI/2;w.position.set(x,.18,z);w.name='wheel';g.add(w)}return g;}
function makeAvatar(x,z){const g=new THREE.Group();const head=sphere(.22,mat(0xffd6b5));head.position.y=1.55;const body=cube(.42,.72,.25,mat(0x0f8fe8));body.position.y=.95;const legs=cube(.38,.65,.24,mat(0x12304a));legs.position.y=.35;g.add(head,body,legs);g.position.set(x,0,z);g.userData={baseX:x,baseZ:z,walk:Math.random()*6};npcs.push(g);return g;}
function sign(txt,x,z){const c=document.createElement('canvas');c.width=512;c.height=160;const g=c.getContext('2d');g.fillStyle='#dffaff';g.fillRect(0,0,512,160);g.fillStyle='#12304a';g.font='bold 46px system-ui';g.fillText(txt,28,88);g.fillStyle='#ffd84d';g.fillRect(28,108,456,16);const p=new THREE.Mesh(new THREE.PlaneGeometry(3.8,1.15),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c)}));p.position.set(x,2.5,z);p.name='sign';scene.add(p)}
function sparks(x,z){for(let i=0;i<24;i++){const p=sphere(.045,mat(i%2?0xffd84d:0x65e6ff));p.position.set(x+(Math.random()-.5)*4,.35+Math.random()*2,z+(Math.random()-.5)*4);p.userData={rise:.5+Math.random()*1.2,base:.35};scene.add(p);particles.push(p)}}
function build(){scene=new THREE.Scene();scene.background=new THREE.Color(0xdffaff);scene.fog=new THREE.Fog(0xdffaff,12,48);clock=new THREE.Clock();camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,1000);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;scene.add(new THREE.HemisphereLight(0xffffff,0x8bdfff,1.9));const sun=new THREE.DirectionalLight(0xfff2b0,3.1);sun.position.set(-6,9,7);sun.castShadow=true;scene.add(sun);const glow=sphere(.9,mat(0xffd84d));glow.position.set(-7,5,-30);glow.name='sunGlow';scene.add(glow);const floor=new THREE.Mesh(new THREE.PlaneGeometry(80,80),glass(0xcaf6ff));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const road=cube(10,.04,42,mat(0x39475a));road.position.set(0,.025,-8);scene.add(road);for(let i=0;i<18;i++){const line=cube(.12,.05,1.4,mat(0xffe66b));line.position.set(0,.07,10-i*2.5);scene.add(line)}const garage=cube(8,4,.18,glass(0xe9fbff));garage.position.set(0,2,4.5);scene.add(garage);const door=cube(4,3,.16,mat(0xffffff));door.position.set(0,1.55,3.9);door.name='door';scene.add(door);const lift=cube(4,4,4,glass(0x9eeaff));lift.position.set(0,2,-16);lift.name='lift';scene.add(lift);const liftFloor=cube(4,.12,4,mat(0xffd84d));liftFloor.position.set(0,.1,-16);scene.add(liftFloor);for(let k=0;k<6;k++){const strip=cube(4,.04,.08,mat(0x65e6ff));strip.position.set(0,.2+k*.55,-14.1);strip.name='glowStrip';scene.add(strip)}car=makeCar();car.position.set(0,0,1.2);scene.add(car);scene.add(makeAvatar(-2,-18),makeAvatar(2,-19),makeAvatar(.8,-21),makeAvatar(-1.2,-23));sign('GAMEIO VER XP',0,-22);sign('SIMULATED IN INDIA',-4,-18);sparks(0,-18);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});}
function hud(){if(document.getElementById('xpHud'))return;const d=document.createElement('div');d.id='xpHud';d.style.cssText='position:fixed;left:0;right:0;bottom:0;height:34vh;z-index:10000;pointer-events:none;background:linear-gradient(transparent,rgba(0,0,0,.58));color:white;font-family:system-ui;font-weight:900';d.innerHTML='<div style="position:absolute;left:50%;bottom:18px;transform:translateX(-50%);width:180px;height:180px;border:18px solid #111;border-radius:50%;box-shadow:0 0 0 5px #ffd84d inset;animation:xpPulse .7s infinite alternate"></div><div style="position:absolute;left:24px;bottom:28px;background:#06233a;padding:10px 14px;border-radius:14px;border:1px solid #65e6ff">RPM ▰▰▰▱<br><span style="color:#ffd84d">VER XP ⚡</span></div><style>@keyframes xpPulse{to{transform:scale(1.035)}}</style>';document.body.appendChild(d)}
function apiLobby(){phase=4;t=0;playXP('lobby')}function apiCars(){phase=1;t=0;playXP('drive')}function apiFish(){phase=4;t=0;playXP('lobby')}
function anim(){requestAnimationFrame(anim);const dt=clock.getDelta();t+=dt;const door=scene.getObjectByName('door');const lift=scene.getObjectByName('lift');const glow=scene.getObjectByName('sunGlow');if(glow)glow.scale.setScalar(1+Math.sin(t*2)*.08);particles.forEach(p=>{p.position.y+=dt*p.userData.rise;if(p.position.y>2.6)p.position.y=p.userData.base;p.rotation.x+=dt});npcs.forEach((n,i)=>{n.position.x=n.userData.baseX+Math.sin(t+n.userData.walk)*.35;n.rotation.y=Math.sin(t*1.5+i)*.5});if(car)car.children.forEach(c=>{if(c.name==='wheel')c.rotation.x+=dt*9});if(phase===0){playXP('drive');hud();camera.position.set(Math.sin(t*3)*.02,1.25+Math.sin(t*7)*.01,2.7);camera.lookAt(0,1.1,-8);if(door)door.position.y=Math.max(3.8,1.55+t*.75);if(t>3){phase=1;t=0}}else if(phase===1){playXP('drive');car.position.z-=dt*5;camera.position.set(Math.sin(t*4)*.045,1.25+Math.sin(t*8)*.018,car.position.z+1.65);camera.lookAt(0,1.05,car.position.z-6);if(car.position.z<-12){phase=2;t=0}}else if(phase===2){playXP('elevator');camera.position.set(Math.sin(t*12)*.015,1.35,-14.4);camera.lookAt(0,1.1,-19);if(lift)lift.position.y=2+Math.sin(t*8)*.035;if(t>2.2){phase=3;t=0}}else if(phase===3){playXP('elevator');if(lift)lift.position.y=2+t*1.7;camera.position.set(Math.sin(t*12)*.025,1.45,-16);camera.lookAt(0,2.2,-22);if(t>2.6){phase=4;t=0}}else{playXP('lobby');document.getElementById('xpHud')?.remove();camera.position.set(Math.sin(t*.4)*1.8,3.5,-24+Math.cos(t*.4)*1.2);camera.lookAt(0,1.2,-18)}renderer.render(scene,camera)}
export function startV8(container){container.innerHTML='';build();container.appendChild(renderer.domElement);anim();window.GameIO3D={api:{lobby:apiLobby,cars:apiCars,fishana:apiFish}};return window.GameIO3D.api}
