import{updateVehicle,hit,worldGrip}from'./physics.js';
const cameras=['Chase','Cockpit','Drone','Cinematic'];
export class WorldEngine{
constructor(canvas,mini,labels){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.mini=mini;this.mctx=mini.getContext('2d');this.labels=labels;this.vehicle=null;this.players=[];this.running=false;this.cameraIndex=0;this.input={throttle:false,brake:false,left:false,right:false,boost:false};this.world='ocean';this.gameName='Fishana';this.pearls=[];this.boss={x:830,y:360};this.lastSync=0;this.lastFps=performance.now();this.frames=0;this.onSync=null;this.onFinish=null;this.t=0;}
start(vehicle,game,avatar,onSync,onFinish){this.vehicle=vehicle;this.world=game.world||'road';this.gameName=game.name;this.onSync=onSync;this.onFinish=onFinish;this.running=true;this.pearls=[{x:360,y:130,taken:false},{x:560,y:290,taken:false},{x:780,y:190,taken:false},{x:445,y:440,taken:false}];requestAnimationFrame(()=>this.frame());}
stop(){this.running=false}
camera(){this.cameraIndex=(this.cameraIndex+1)%cameras.length;this.labels.camera.textContent='Camera '+cameras[this.cameraIndex]}
setPlayers(players){this.players=players||[]}
toggleFps(){return true}
evolve(){if(this.vehicle){this.vehicle.evolution=Math.min(3,(this.vehicle.evolution||0)+1);this.vehicle.score+=75}}
frame(){if(!this.running||!this.vehicle)return;this.t+=.016;updateVehicle(this.vehicle,this.input,this.world);for(const p of this.pearls){if(!p.taken&&hit(this.vehicle,p,36)){p.taken=true;this.vehicle.score+=40;this.vehicle.pearls=(this.vehicle.pearls||0)+1;if(this.world==='ocean'&&this.vehicle.pearls>=2)this.vehicle.evolution=Math.max(this.vehicle.evolution||0,1);if(this.world==='ocean'&&this.vehicle.pearls>=4)this.vehicle.evolution=Math.max(this.vehicle.evolution||0,2)}}if((this.world==='ocean'||this.world==='deep')&&hit(this.vehicle,this.boss,52)){this.vehicle.score=Math.max(0,this.vehicle.score-10);this.vehicle.speed*=-.35}this.draw();this.drawMini();this.frames++;const now=performance.now();if(now-this.lastFps>500){if(this.labels.fps)this.labels.fps.textContent='FPS '+Math.round(this.frames*1000/(now-this.lastFps));this.frames=0;this.lastFps=now}this.labels.score.textContent='Score '+Math.floor(this.vehicle.score);this.labels.lap.textContent=this.world==='hub'?'Hub':'Lap '+Math.min(this.vehicle.lap,3)+'/3';if(this.labels.evolve)this.labels.evolve.textContent='Evolution '+(this.vehicle.evolution||0);if(this.onSync&&Date.now()-this.lastSync>700){this.lastSync=Date.now();this.onSync(this.vehicle)}if(this.vehicle.finished&&this.onFinish){this.running=false;this.onFinish(this.vehicle);return}requestAnimationFrame(()=>this.frame())}
bg(){const map={hub:['#dffaff','#ffffff','#64d9ff'],road:['#86e4ff','#e7fbff','#5d6068'],gt:['#cfe8ff','#f9fbff','#3c4555'],rally:['#d3ffbf','#fff6d5','#8a5b31'],kart:['#ffecd1','#eaffff','#575757'],space:['#07132b','#173c87','#ffffff'],lava:['#ffb36b','#ffe5c0','#4d1a08'],ice:['#e9fdff','#b7f1ff','#8ae6ff'],dino:['#c5ffbd','#fff5cd','#6d4827'],dragon:['#ffe1d4','#f8fbff','#7b2738'],desert:['#ffe1a3','#fff8df','#b3742e'],city:['#cbe9ff','#ffffff','#444b61'],moon:['#0b1838','#cfd7e6','#c9c9c9'],arena:['#0b1022','#263e8d','#8f5cff'],obby:['#e8f8ff','#fff','#5cc1ff']};return map[this.world]||['#5bdfff','#e8ffff','#0b9bd2']}
roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();ctx.stroke()}
drawSky(ctx){const[a,b]=this.bg();const g=ctx.createLinearGradient(0,0,0,330);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,this.canvas.width,330);ctx.fillStyle='rgba(255,255,255,.55)';for(let i=0;i<8;i++){let x=(i*170+this.t*28)%1250-100;let y=70+(i%4)*44;ctx.beginPath();ctx.ellipse(x,y,62,20,0,0,7);ctx.fill()}ctx.fillStyle=this.world==='space'?'#102150':this.world==='lava'?'#7a2c13':'rgba(255,255,255,.48)';ctx.beginPath();ctx.moveTo(0,310);ctx.lineTo(190,200);ctx.lineTo(380,310);ctx.lineTo(560,180);ctx.lineTo(760,310);ctx.lineTo(960,210);ctx.lineTo(1100,310);ctx.lineTo(1100,620);ctx.lineTo(0,620);ctx.closePath();ctx.fill()}
drawHub(ctx){ctx.fillStyle='#ffffffaa';ctx.strokeStyle='#82dcff';for(let i=0;i<5;i++){this.roundRect(ctx,120+i*165,120+(i%2)*85,120,70,20)}ctx.fillStyle='#12304a';ctx.font='28px system-ui';ctx.fillText('GameIO Social Hub',360,70);ctx.font='16px system-ui';['Fishana','Cars','Cards','Space','Obby'].forEach((x,i)=>ctx.fillText(x,132+i*165,160+(i%2)*85))}
drawPerspective(ctx){if(this.world==='hub'||this.world==='ocean')return false;const top=300,bottom=620,cx=550;ctx.fillStyle=this.world==='rally'?'#8a5b31':this.world==='desert'?'#c9903d':this.world==='arena'?'#30215f':'#4b5663';ctx.beginPath();ctx.moveTo(cx-75,top);ctx.lineTo(cx+75,top);ctx.lineTo(1040,bottom);ctx.lineTo(60,bottom);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(cx-75,top);ctx.lineTo(60,bottom);ctx.moveTo(cx+75,top);ctx.lineTo(1040,bottom);ctx.stroke();ctx.setLineDash([26,26]);ctx.beginPath();ctx.moveTo(cx,top);ctx.lineTo(cx,bottom);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<12;i++){let y=top+i*31+(this.vehicle.speed*8%31);let s=(y-top)/(bottom-top);ctx.strokeStyle='rgba(255,255,255,'+(0.15+s*.45)+')';ctx.lineWidth=1+s*4;ctx.beginPath();ctx.moveTo(cx-80-s*420,y);ctx.lineTo(cx+80+s*420,y);ctx.stroke()}return true}
drawTrack(ctx){this.drawSky(ctx);if(this.world==='hub'){this.drawHub(ctx);return}if(this.drawPerspective(ctx)){ctx.fillStyle='#fff';ctx.font='28px system-ui';ctx.fillText('FINISH',860,300);return}const track=this.bg()[2];ctx.strokeStyle=track;ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(90,300);ctx.bezierCurveTo(235,65,565,75,765,155);ctx.bezierCurveTo(1030,250,900,520,560,490);ctx.bezierCurveTo(250,462,120,425,90,300);ctx.stroke();ctx.fillStyle='#fff';ctx.font='28px system-ui';ctx.fillText('FINISH',860,300)}
drawCar(ctx,x,y,a,ghost=false){ctx.save();ctx.translate(x,y);ctx.rotate(a||0);ctx.globalAlpha=ghost?.6:1;ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=12;ctx.fillStyle='#0f8fe8';ctx.strokeStyle='#05324c';ctx.lineWidth=3;this.roundRect(ctx,-34,-18,68,36,14);ctx.fillStyle='#bff4ff';this.roundRect(ctx,-10,-14,28,28,10);ctx.fillStyle='#111';ctx.fillRect(-25,-24,16,8);ctx.fillRect(12,-24,16,8);ctx.fillRect(-25,16,16,8);ctx.fillRect(12,16,16,8);ctx.fillStyle='#fff';ctx.fillRect(22,-7,10,5);ctx.restore();ctx.globalAlpha=1}
drawFishana(ctx,x,y,a,evo=0,ghost=false){ctx.save();ctx.translate(x,y);ctx.rotate(a||0);ctx.globalAlpha=ghost?.65:1;ctx.shadowColor='rgba(0,90,120,.35)';ctx.shadowBlur=16;ctx.strokeStyle='#05324c';ctx.lineWidth=3;if(evo===0){ctx.fillStyle='#24d3ff';ctx.beginPath();ctx.ellipse(0,0,36,20,0,0,7);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-36,0);ctx.lineTo(-58,-20);ctx.lineTo(-58,20);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(18,-7,5,0,7);ctx.fill()}else if(evo===1){ctx.fillStyle='#45df8a';this.roundRect(ctx,-28,-14,56,28,14);ctx.beginPath();ctx.moveTo(-28,0);ctx.lineTo(-48,-12);ctx.lineTo(-48,12);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillRect(-12,14,10,18);ctx.fillRect(12,14,10,18)}else if(evo===2){ctx.fillStyle='#9b6bff';ctx.beginPath();ctx.arc(0,-16,18,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#6d4ad9';this.roundRect(ctx,-18,0,36,48,14);ctx.fillStyle='#6d4ad9';ctx.fillRect(-30,8,12,35);ctx.fillRect(18,8,12,35)}else{ctx.fillStyle='#f0fbff';ctx.beginPath();ctx.arc(0,-18,17,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#27c8ff';this.roundRect(ctx,-20,0,40,52,16);ctx.fillStyle='#12304a';ctx.fillRect(-26,14,12,30);ctx.fillRect(14,14,12,30)}ctx.restore();ctx.globalAlpha=1}
drawHero(ctx,x,y,a,ghost=false){if(this.world==='ocean')return this.drawFishana(ctx,x,y,a,this.vehicle?.evolution||0,ghost);if(['road','ice','gt','rally','kart','desert','city'].includes(this.world))return this.drawCar(ctx,x,y,a,ghost);ctx.save();ctx.translate(x,y);ctx.rotate(a||0);ctx.globalAlpha=ghost?.6:1;ctx.fillStyle='#7bdcff';ctx.strokeStyle='#05324c';ctx.lineWidth=3;this.roundRect(ctx,-24,-24,48,48,16);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-36,15,0,7);ctx.fill();ctx.stroke();ctx.restore();ctx.globalAlpha=1}
draw(){const ctx=this.ctx,c=this.canvas,v=this.vehicle;ctx.clearRect(0,0,c.width,c.height);this.drawTrack(ctx);for(const p of this.pearls){if(!p.taken&&this.world!=='hub'){ctx.fillStyle='#fff';ctx.strokeStyle='#0f8fe8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,14,0,7);ctx.fill();ctx.stroke()}}if(this.world==='ocean'){ctx.fillStyle='#12304a';ctx.beginPath();ctx.ellipse(this.boss.x,this.boss.y,48,22,0,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(this.boss.x+20,this.boss.y-5,5,0,7);ctx.fill()}for(const p of this.players){if(!p||p.id===localStorage.gid)continue;this.drawHero(ctx,p.x||100,p.y||100,0,true);ctx.fillStyle='#12304a';ctx.font='14px system-ui';ctx.fillText(p.name||'friend',(p.x||100)-18,(p.y||100)+42)}this.drawHero(ctx,v.x,v.y,v.angle,false);ctx.fillStyle='#12304a';ctx.font='20px system-ui';ctx.fillText(this.gameName,20,30);ctx.fillText('Speed '+Math.abs(v.speed).toFixed(1),20,56);ctx.fillText('Grip '+worldGrip(this.world).toFixed(2),20,82)}
drawMini(){const ctx=this.mctx,c=this.mini,v=this.vehicle;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#001826';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#69e6ff';ctx.lineWidth=3;ctx.strokeRect(12,16,136,68);ctx.fillStyle='#fff';ctx.fillRect(Math.min(150,Math.max(8,v.x/7)),Math.min(92,Math.max(6,v.y/6)),6,6)}
}
