import{updateVehicle,hit,worldGrip}from'./physics.js';
const cameras=['Chase','Cockpit','Drone','Cinematic'];
export class WorldEngine{
constructor(canvas,mini,labels){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.mini=mini;this.mctx=mini.getContext('2d');this.labels=labels;this.vehicle=null;this.players=[];this.running=false;this.cameraIndex=0;this.input={throttle:false,brake:false,left:false,right:false,boost:false};this.world='ocean';this.gameName='Fishana';this.pearls=[];this.boss={x:830,y:360};this.lastSync=0;this.lastFps=performance.now();this.frames=0;this.onSync=null;this.onFinish=null;}
start(vehicle,game,avatar,onSync,onFinish){this.vehicle=vehicle;this.world=game.world||'road';this.gameName=game.name;this.onSync=onSync;this.onFinish=onFinish;this.running=true;this.pearls=[{x:360,y:130,taken:false},{x:560,y:290,taken:false},{x:780,y:190,taken:false},{x:445,y:440,taken:false}];requestAnimationFrame(()=>this.frame());}
stop(){this.running=false}
camera(){this.cameraIndex=(this.cameraIndex+1)%cameras.length;this.labels.camera.textContent='Camera '+cameras[this.cameraIndex]}
setPlayers(players){this.players=players||[]}
toggleFps(){return true}
evolve(){if(this.vehicle){this.vehicle.evolution=Math.min(3,(this.vehicle.evolution||0)+1);this.vehicle.score+=75}}
frame(){if(!this.running||!this.vehicle)return;updateVehicle(this.vehicle,this.input,this.world);for(const p of this.pearls){if(!p.taken&&hit(this.vehicle,p,36)){p.taken=true;this.vehicle.score+=40;this.vehicle.pearls=(this.vehicle.pearls||0)+1;if(this.world==='ocean'&&this.vehicle.pearls>=2)this.vehicle.evolution=Math.max(this.vehicle.evolution||0,1);if(this.world==='ocean'&&this.vehicle.pearls>=4)this.vehicle.evolution=Math.max(this.vehicle.evolution||0,2)}}if((this.world==='ocean'||this.world==='deep')&&hit(this.vehicle,this.boss,52)){this.vehicle.score=Math.max(0,this.vehicle.score-10);this.vehicle.speed*=-.35}this.draw();this.drawMini();this.frames++;const now=performance.now();if(now-this.lastFps>500){if(this.labels.fps)this.labels.fps.textContent='FPS '+Math.round(this.frames*1000/(now-this.lastFps));this.frames=0;this.lastFps=now}this.labels.score.textContent='Score '+Math.floor(this.vehicle.score);this.labels.lap.textContent=this.world==='hub'?'Hub':'Lap '+Math.min(this.vehicle.lap,3)+'/3';if(this.labels.evolve)this.labels.evolve.textContent='Evolution '+(this.vehicle.evolution||0);if(this.onSync&&Date.now()-this.lastSync>700){this.lastSync=Date.now();this.onSync(this.vehicle)}if(this.vehicle.finished&&this.onFinish){this.running=false;this.onFinish(this.vehicle);return}requestAnimationFrame(()=>this.frame())}
bg(){const map={hub:['#dffaff','#ffffff','#64d9ff'],road:['#86e4ff','#e7fbff','#5d6068'],gt:['#cfe8ff','#f9fbff','#3c4555'],rally:['#d3ffbf','#fff6d5','#8a5b31'],kart:['#ffecd1','#eaffff','#575757'],space:['#07132b','#173c87','#ffffff'],lava:['#ffb36b','#ffe5c0','#4d1a08'],ice:['#e9fdff','#b7f1ff','#8ae6ff'],dino:['#c5ffbd','#fff5cd','#6d4827'],dragon:['#ffe1d4','#f8fbff','#7b2738'],desert:['#ffe1a3','#fff8df','#b3742e'],city:['#cbe9ff','#ffffff','#444b61'],moon:['#0b1838','#cfd7e6','#c9c9c9'],arena:['#0b1022','#263e8d','#8f5cff'],obby:['#e8f8ff','#fff','#5cc1ff']};return map[this.world]||['#5bdfff','#e8ffff','#0b9bd2']}
drawHub(ctx){ctx.fillStyle='#ffffffaa';for(let i=0;i<5;i++){ctx.beginPath();ctx.roundRect(120+i*165,120+(i%2)*85,120,70,20);ctx.fill()}ctx.fillStyle='#12304a';ctx.font='28px system-ui';ctx.fillText('GameIO Social Hub',360,70);ctx.font='38px system-ui';['🎣','🏎️','🃏','🚀','🧗'].forEach((x,i)=>ctx.fillText(x,160+i*165,170+(i%2)*85))}
drawTrack(ctx){const[a,b,track]=this.bg();const grd=ctx.createLinearGradient(0,0,0,this.canvas.height);grd.addColorStop(0,a);grd.addColorStop(1,b);ctx.fillStyle=grd;ctx.fillRect(0,0,this.canvas.width,this.canvas.height);if(this.world==='hub'){this.drawHub(ctx);return}ctx.strokeStyle=track;ctx.lineWidth=this.world==='ocean'?4:76;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(90,300);ctx.bezierCurveTo(235,65,565,75,765,155);ctx.bezierCurveTo(1030,250,900,520,560,490);ctx.bezierCurveTo(250,462,120,425,90,300);ctx.stroke();ctx.fillStyle='#fff';ctx.font='30px system-ui';ctx.fillText('🏁',900,300)}
icon(){if(this.world==='ocean')return['🐟','🦎','🐒','🧑‍🚀'][this.vehicle?.evolution||0]||'🐟';if(this.world==='hub')return'🧑';if(['road','ice','gt','rally','kart','desert','city'].includes(this.world))return'🏎️';if(this.world==='space')return'🚀';if(this.world==='dino')return'🦖';if(this.world==='dragon')return'🐉';if(this.world==='lava')return'🏃';return'🐟'}
draw(){const ctx=this.ctx,c=this.canvas,v=this.vehicle;ctx.clearRect(0,0,c.width,c.height);this.drawTrack(ctx);for(const p of this.pearls){if(!p.taken&&this.world!=='hub'){ctx.font='34px system-ui';ctx.fillText(this.world==='ocean'?'💎':'⭐',p.x,p.y)}}if(this.world==='ocean'){ctx.font='52px system-ui';ctx.fillText('🦈',this.boss.x,this.boss.y)}for(const p of this.players){if(!p||p.id===localStorage.gid)continue;ctx.globalAlpha=.75;ctx.font='34px system-ui';ctx.fillText(p.avatar||'😎',p.x||100,p.y||100);ctx.font='14px system-ui';ctx.fillStyle='#12304a';ctx.fillText(p.name||'friend',(p.x||100)-8,(p.y||100)+24);ctx.globalAlpha=1}ctx.save();ctx.translate(v.x,v.y);ctx.rotate(v.angle);ctx.font='48px system-ui';ctx.fillText(this.icon(),-22,16);ctx.restore();ctx.fillStyle='#12304a';ctx.font='20px system-ui';ctx.fillText(this.gameName,20,30);ctx.fillText('Speed '+Math.abs(v.speed).toFixed(1),20,56);ctx.fillText('Grip '+worldGrip(this.world).toFixed(2),20,82)}
drawMini(){const ctx=this.mctx,c=this.mini,v=this.vehicle;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#001826';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#69e6ff';ctx.lineWidth=3;ctx.strokeRect(12,16,136,68);ctx.fillStyle='#fff';ctx.fillRect(Math.min(150,Math.max(8,v.x/7)),Math.min(92,Math.max(6,v.y/6)),6,6)}
}
